---
branches:
  - stable
  - beta
  - pm5
projects:
  RolesManager:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
      - src: AID-LEARNING/LanguageSystem/libLanguageSystem
        version: ^1.0.4
      - src: AID-LEARNING/ExtraEvent/libEventAttribute
        version: ^1.0.2
        branch: pm5
      - src: AID-LEARNING/libExtraPath/libExtraPathConfig
        version: ^1.0.1
        branch: pm5
      - src: AID-LEARNING/FormAPI/libFormAPI
        version: ^2.1.0
      - src: AID-LEARNING/IconForm/libIconForm
        version: ^1.0.0
      - src: AID-LEARNING/libDataBase/libDataBase
        version: ^1.0.3
      - src: AID-LEARNING/Commando/Commando
        version: ^3.0.0
        branch: pm5
...