branches:
  - beta
  - master
projects:
  RolesManager:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
      - src: AID-LEARNING/LanguageSystem/libLanguageSystem
        version: ^1.0.0
      - src: AID-LEARNING/libExtraPath/libExtraPathConfig
        version: ^1.0.0
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
