branches:
  - beta
  - master
projects:
  RolesManager:
  path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
      - src: SenseiTarzan/LanguageSystem/libLanguageSystem
        version: ^1.0.0
      - src: SenseiTarzan/Path/libPath-Config
        version: ^1.0.0
      - src: CortexPE/Commando
        version: ^3.1.0
