name: RoleManager
authors:
  - SenseiTarzan
version: 1.0.3
main: SenseiTarzan\RoleManager\Main
api: 5.0.0
permissions:
  rolemanager.command.role.permission:
    description: "Allows to see the command role"
    default: op
  rolemanager.command.nameCustom.permission:
    description: "Allows you to set a custom role name"
    default: op
  rolemanager.command.set-role.permission:
    description: "Allows to put a role a player"
    default: true
  rolemanager.command.suffix.permission:
    description: "Allows you to put a suffix to a player"
    default: op
  rolemanager.command.prefix.permission:
    description: "Allows to put a prefix to a player"
    default: op
  rolemanager.command.set-permissions.permission:
    description: "Allows you to set one or more permissions for a player"
    default: op
  rolemanager.command.add-permissions.permission:
    description: "Allows you to add one or more permissions to a player"
    default: op
  rolemanager.command.sub-permissions.permission:
    description: "Allows you to remove one or more permissions from a player"
    default: op
  rolemanager.command.create-role.permission:
    description: "Allows you to create roles in UI"
    default: op
  rolemanager.command.modified-role.permission:
    description: "Allows you to modify roles in UI"
    default: op
  rolemanager.command.reload-role.permission:
    description: "Allows to refresh the roles in the files"
    default: op
